---
common:
    title_icon_set: mono-white         # Iconset to use for module icons displayed in top navbar.
    navmenu_show_icons: true                 # Whether or not to show icons in the side navigation menu.  May degrade performance.
    navmenu_icon_set: mono-white             # If navmenu_show_icons is true, which iconset to use for module icons.

    portlet_icon_set: BluSqrBottomFill       # Iconset to use in the title of portlets when using iconset images for the titleImage

    primary_font_family: Helvetica Neue, Helvetica, Arial, sans-serif  # Font family for most of the text in the app
    primary_font_weight: normal              # Font weight for most of the text in the app
    primary_font_style: normal               # Font style for most of the text in the app
    base_font_size: 16px                     # Base font size. Almost all of the other font sizes throughout your web app will be calculated as percentages of this base font size. Should be in px.
    primary_text_color: '#000000'            # Primary text color for most text and navigation elements throughout app
    secondary_text_color: '#000000'          # Text color for smallprint, fineprint, legends, labels, nonselected tabs, and text in secondary nav lists
    tertiary_text_color: '#808080'           # Text color for secondary nav list smallprint

    primary_heading_font_family: 'Georgia, serif'  # Font family for <h1> elements, including content item titles (leave null to use primary_font_family)
    primary_heading_font_size: 1.5rem        # Font size for <h1> elements. Should be in rem.
    primary_heading_font_weight: normal      # Font weight for <h1> elements
    primary_heading_font_style: normal       # Font style for <h1> elements
    primary_heading_text_color: '#000000'    # Text color for <h1> elements

    secondary_heading_font_family: null      # Font family for <h2> elements (leave null to use primary_font_family)
    secondary_heading_font_size: 1.25rem     # Font size for <h2> elements
    secondary_heading_font_weight: normal    # Font weight for <h2> elements
    secondary_heading_font_style: normal     # Font style for <h2> elements
    secondary_heading_text_color: '#000000'  # Text color for <h2> elements

    tertiary_heading_font_family: null       # Font family for <h3> and <h4> elements, including grouped list headers (leave null to use primary_font_family)
    tertiary_heading_font_size: 1rem         # Font size for <h3> and <h4> elements. Should be in rem.
    tertiary_heading_font_weight: bold       # Font weight for <h3> and <h4> elements
    tertiary_heading_font_style: normal      # Font style for <h3> elements
    tertiary_heading_text_color: '#333333'   # Text color for <h3> and <h4> elements

    deck_font_family: 'Georgia, serif'       # Font family for dek/deck and introduction paragraphs in detail pages
    deck_font_style: normal                  # Font style for dek/deck and introduction paragraphs in detail pages
    deck_text_color: '#707070'               # Color for dek/deck and introduction paragraphs

    focal_link_color: '#3366cc'              # Color of text links within focal content areas
    focal_link_hover_color: '#3399ff'        # Hover color (only applies to desktops and cursor-driven mobile devices)
    focal_link_active_color: '#003366'       # Active color
    link_text_decoration: none               # Text decoration for links embedded within body content, including web content. Acceptable values: "none", "underline" (empty value uses browser's default link decoration, which is generally underline)

    nonfocal_text_color: '#404040'           # Text and link text that appear on the body background, e.g., within nonfocal elements
    nonfocal_secondary_text_color: '#808080' # Secondary text and link text that appear on the body background, e.g., within nonfocal elements
    nonfocal_heading_color: '#333333'        # Color for all <h1>, <h2>, <h3>, and <h4> elements that appear on the body background, e.g., within nonfocal elements
    nonfocal_link_color: '#3366cc'           # Color of text links that appear on the body background, e.g., within nonfocal elements
    nonfocal_link_hover_color: '#3399ff'     # Hover color of text links that appear on the body background, e.g., within nonfocal elements (only applies to desktops and cursor-driven mobile devices)
    nonfocal_link_active_color: '#003366'     # Active color of text links that appear on the body background, e.g., within nonfocal elements

    focal_background_color: '#f7f7f7'        # Background color for elements that contain the primary focus of a page, e.g., navigation and results lists, content detail views, tab bodies, active tabs, etc. Generally white or very light grey/neutral.
    subfocal_background_color: '#f0f0f0'     # Background color for elements which generally have focal background color, but are nested within an element that already has focal_background_color.

    focal_border_color: '#c9c9c9'            # Color of borders around focal content areas and navigation and results lists, and between list items

    navbar_background_color: '#56A0D3'       # Background color behind navbar. Also serves as tint color for system-drawn buttons on the UINavigationBar in iOS6 native.
    navbar_text_color: '#ffffff'             # Color of navigation-bar text (page title, button labels, etc.)
    navbar_border_color: '#56A0D3'

    navmenu_background_color: '#56A0D3'      # Background color for navigation menu
    navmenu_background_image: none           # Optional# use "none" if no image is required, or CSS format e.g., "url(kgo_image(navmenu-back.jpg))"
    navmenu_text_color: '#dddddd'            # Color of non-link text and section headings in nav menu
    navmenu_list_background_color: '#56A0D3' # Background color of actual navigation list(s) within nav menu (does not apply to Android native)
    navmenu_link_color: '#dddddd'            # Color of text links (module names) within navigation lists in nav menu
    navmenu_link_selected_color: '#ffffff'   # Color of selected module name in nav menu
    navmenu_link_hover_color: '#ffffff'      # Hover (mouseover) color of text links (module names) in nav menu
    navmenu_link_active_color: '#ffffff'     # Active (mousedown) color of text links (module names) in nav menu
    navmenu_border_color: '#363636'          # Color of divider line between rows in nav menu
    navmenu_footer_height: 120px             # The height of the footer.  Make sure to test with the largest font size when determining this value.
    navmenu_footer_text_color: '#808080'     # Color of text and text links in site footer at bottom of navmenu

    highlight_background_color: '#007eff'    # Highlight color for pressed state of list items. Does not apply to Android native.
    highlight_text_color: '#ffffff'          # Text color for highlighted/pressed state of list items. Does not apply to Android native.
    list_accessory_color: '#737373'          # Color of accessory icons in list views.

    # KGOUIPortlets
    portlet_header_title_color: '#333333'    # Text color for the title (generally module or feed name) in the portlet header bar
    portlet_header_font_size: '0.75rem'      # Font size for title in the portlet header bar
    portlet_header_background_color: '#f3f3f3'  # Background color for the portlet header bar. Must be RGB hex value. Used as fallback for older browsers that don't understand RGBA color.
    portlet_header_background_color_rgba: 'rgba(230,230,230,0.8)' # Background color for the portlet header bar. Must be rgba value. Used on modern browers and native apps.

    # KGOUIList
    list_section_heading_background_color: '#808080'    # Background color for section headings in sectioned lists
    list_section_heading_text_color: '#ffffff'      # Text color for section headings in sectioned lists

    # KGOUIFormSearch, KGOUISearch*
    search_button_background_color: null     # Background color for search buttons. Applies to web only. Set to null to default to focal_link_color.
    search_button_text_color: '#ffffff'      # Color of text and search icon within search buttons. Must have strong contrast with search_button_background_color.

    # KGOUIToolbar
    toolbar_background: '#262626'            # Background color for toolbar
    toolbar_font_weight: bold                # Font weight for text elements within toolbar (aside from text elements whose weight is otherwise defined)
    toolbar_text_color: '#cccccc'            # Color of text elements within toolbar (aside from text elements whose color is otherwise defined)
    toolbar_button_border_style: light       # Style of borders of buttons inside toolbar. Valid values: 'light', 'dark', or 'none'

    # KGOMenu
    menu_text_color: null                    # Color of text within dropdown menu invoked from within page body (note that dropdown menus invoked from toolbars use toolbar_text_color). Set to null to default to navmenu_text_color.
    menu_background_color: null         # Background color for dropdown menu invoked from within page body (note that dropdown menus invoked from toolbars use toolbar_background). Set to null to default tonavmenu_background_color.
    menu_item_border_color: null             # Color of border lines between dropdown menu items (note that dropdown menus invoked from toolbars use a line color based on toolbar_button_border_style). Set to null to default to navmenu_border_color.

    # KGOUIMap
    map_polyline_stroke_color: '#666666' # defaults to primary_text_color
    map_polyline_stroke_alpha: 0.8       # defaults to 1
    map_polyline_stroke_width: 3         # defaults to border_radius_tight
    map_polygon_fill_color: '#999999'    # defaults to secondary_text_color
    map_polygon_fill_alpha: 0.5          # defaults to 0.5

    # KGOUIObject styles:
    # Styles are the only theme variable which can be overridden by modules.
    # All other site theme variables must be overridden at the site level.
    styles:
        kgoui_page:
            default:
                body_background_color: '#e0e0e0'   # Overall body background color of the app. Should have at least slight contrast with focal_background_color. Best results are generally seen with a light grey/neutral color.
                body_background_image: null        # Overall body background image. Optional, use null if no image is required, or actual filename, e.g., "body-background.jpg". This image must be in the theme's common/images/ directory.
                body_background_position: top left # CSS background-position for the body background image (if specified)
                body_background_repeat: repeat     # CSS background-repeat for the body background image (if specified)
                body_background_size: auto         # CSS background-size for the body background image (if specified)
                body_background_attachment: scroll # CSS background-attachment for the body background image (if specified)
                footer_text_color: null            # Color of text and text links in page footer, including 'Back to Top' and copyright notice.
        kgoui_list_navigation: # Styles for list navigation in page content
            default:
                heading_text_color: null # Text color for section headings (if any) in list-style layout. Set to null to default to global nonfocal_text_color.
                border_color: null # Border color around and between modules in list-style layouts. Set to null to default to global focal_border_color.

text:        # Theme parameters that apply specifically to basic, text-based devices (such as feature phones, older BlackBerries, etc.)
    homelink_image_width: 35px              # Width of branding/home image at the top of every Basic page
    homelink_image_height: 35px             # Height of branding/home image at the top of every Basic page
    homelink_image_hides_site_title: false  # If true, will hide site title when the homelink image is next to it. Used for wide homelink images which contain the site title.  This setting does not affect screen readers because the homelink image will always have the site title in its alt text.
    tertiary_heading_font_size: 100%        # Font size for <h3> and <h4> elements. Use a percent value.

large:       # Theme parameters that apply specifically to large-screen devices (tablets and desktops)
    homelink_image_width: 180px              # Width, in pixels, for the homelink image at the left side of the top navigation bar
    homelink_image_hides_site_title: false   # If true, will hide site title when the homelink image is next to it. Used for wide homelink images which contain the site title.  This setting does not affect screen readers because the homelink image will always have the site title in its alt text.

common-ios-native:      # Theme parameters that apply specifically to native iOS 7 apps
    list_section_heading_background_color: '#e9e9e9'    # Background color for section headings in sectioned lists - generally lighter on iOS 7
    list_section_heading_text_color: '#000000'      # Text color for section headings in sectioned lists
    highlight_background_color: '#d3d3d3'    # Highlight color for pressed state of list items. iOS 7-style apps typically have very light-colored pressed state.
    highlight_text_color: '#333333'          # Text color for pressed state of list items.
    navbar_secondary_color: '#e9e9e9'        # Color of secondary elements in the iOS 7 navbar: 'Back' button text label and left-facing arrow, and 3-bar 'Menu' button. Should have strongly legible contrast with navbar_background_color. Can be slightly lower-contrast than navbar_text_color (for better visual hierarchy).
    status_bar_content_style: 'light'        # Status bar text color on iOS7. Can be either "light" or "dark". Use "light" when navbar_background_color is dark, and "dark" if navbar_background_color is light. iOS default (dark) will be applied if a valid value is not provided.
    navbar_translucent: false                # See https://developer.apple.com/library/ios/documentation/UIKit/Reference/UINavigationBar_Class/Reference/UINavigationBar.html#//apple_ref/occ/instp/UINavigationBar/translucent
...

